[package]
name = "eidolon-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Universal C ABI dynamic and static library for Godot, Unreal Engine, Unity, and custom game engines."

[lib]
name = "eidolon"
crate-type = ["cdylib", "staticlib", "rlib"]

[lints]
workspace = true

[dependencies]
eidolon-core = { workspace = true }
eidolon-net = { workspace = true }
eidolon-client = { workspace = true }
