//! Cryptographic session association, challenge-response handshake, and replay protection.
//!
//! Provides authenticated session management for UDP clients using native HMAC-SHA256,
//! 64-bit sliding replay windows, and session nonce tracking with zero dynamic heap allocations.

use crate::crypto::{constant_time_eq, hmac_sha256};
use crate::error::NetError;

/// Length of cryptographic nonces in bytes.
pub const NONCE_LEN: usize = 16;

/// Wire length of ConnectChallengeRequest: account_id (8) + client_nonce (16) + version (2).
pub const CHALLENGE_REQ_LEN: usize = 26;

/// Wire length of ConnectChallengeResponse: server_nonce (16) + auth_cookie (32).
pub const CHALLENGE_RESP_LEN: usize = 48;

/// Wire length of ConnectFinalizeRequest: account_id (8) + auth_cookie (32) + client_proof (32).
pub const FINALIZE_REQ_LEN: usize = 72;

/// Wire length of ConnectFinalizeResponse: session_id (8) + authority_epoch (4) + server_proof (32).
pub const FINALIZE_RESP_LEN: usize = 44;

/// Initial client handshake request initiating association.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectChallengeRequest {
    /// Account identifier attempting to connect.
    pub account_id: u64,
    /// Client-generated random entropy nonce.
    pub client_nonce: [u8; NONCE_LEN],
    /// Client wire protocol version.
    pub protocol_version: u16,
}

impl ConnectChallengeRequest {
    /// Encodes request into destination byte slice.
    pub fn write_to(&self, out: &mut [u8]) -> Result<usize, NetError> {
        if out.len() < CHALLENGE_REQ_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: CHALLENGE_REQ_LEN,
                actual_len: out.len(),
            });
        }
        let (acc_bytes, rest) = out.split_at_mut(8);
        acc_bytes.copy_from_slice(&self.account_id.to_be_bytes());

        let (nonce_bytes, ver_bytes) = rest.split_at_mut(NONCE_LEN);
        nonce_bytes.copy_from_slice(&self.client_nonce);

        let v_bytes = self.protocol_version.to_be_bytes();
        if let Some(dst) = ver_bytes.get_mut(..2) {
            dst.copy_from_slice(&v_bytes);
        }
        Ok(CHALLENGE_REQ_LEN)
    }

    /// Parses request from raw byte slice with strict bounds checking.
    pub fn read_from(src: &[u8]) -> Result<Self, NetError> {
        if src.len() < CHALLENGE_REQ_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: CHALLENGE_REQ_LEN,
                actual_len: src.len(),
            });
        }
        let mut acc_buf = [0u8; 8];
        if let Some(s) = src.get(..8) {
            acc_buf.copy_from_slice(s);
        }
        let account_id = u64::from_be_bytes(acc_buf);

        let mut client_nonce = [0u8; NONCE_LEN];
        if let Some(s) = src.get(8..24) {
            client_nonce.copy_from_slice(s);
        }

        let mut ver_buf = [0u8; 2];
        if let Some(s) = src.get(24..26) {
            ver_buf.copy_from_slice(s);
        }
        let protocol_version = u16::from_be_bytes(ver_buf);

        Ok(Self {
            account_id,
            client_nonce,
            protocol_version,
        })
    }
}

/// Server challenge response containing server nonce and stateless cookie.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectChallengeResponse {
    /// Server-generated random entropy nonce.
    pub server_nonce: [u8; NONCE_LEN],
    /// Stateless authentication cookie generated by server secret.
    pub auth_cookie: [u8; 32],
}

impl ConnectChallengeResponse {
    /// Encodes response into destination byte slice.
    pub fn write_to(&self, out: &mut [u8]) -> Result<usize, NetError> {
        if out.len() < CHALLENGE_RESP_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: CHALLENGE_RESP_LEN,
                actual_len: out.len(),
            });
        }
        let (nonce_bytes, cookie_bytes) = out.split_at_mut(NONCE_LEN);
        nonce_bytes.copy_from_slice(&self.server_nonce);
        if let Some(dst) = cookie_bytes.get_mut(..32) {
            dst.copy_from_slice(&self.auth_cookie);
        }
        Ok(CHALLENGE_RESP_LEN)
    }

    /// Parses response from raw byte slice with strict bounds checking.
    pub fn read_from(src: &[u8]) -> Result<Self, NetError> {
        if src.len() < CHALLENGE_RESP_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: CHALLENGE_RESP_LEN,
                actual_len: src.len(),
            });
        }
        let mut server_nonce = [0u8; NONCE_LEN];
        if let Some(s) = src.get(..NONCE_LEN) {
            server_nonce.copy_from_slice(s);
        }

        let mut auth_cookie = [0u8; 32];
        if let Some(s) = src.get(NONCE_LEN..NONCE_LEN + 32) {
            auth_cookie.copy_from_slice(s);
        }

        Ok(Self {
            server_nonce,
            auth_cookie,
        })
    }
}

/// Client finalization request presenting cryptographic proof of account token.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectFinalizeRequest {
    /// Account identifier.
    pub account_id: u64,
    /// Stateless authentication cookie returned in challenge response.
    pub auth_cookie: [u8; 32],
    /// HMAC proof computed over cookie and nonces using client secret token.
    pub client_proof: [u8; 32],
}

impl ConnectFinalizeRequest {
    /// Encodes request into destination byte slice.
    pub fn write_to(&self, out: &mut [u8]) -> Result<usize, NetError> {
        if out.len() < FINALIZE_REQ_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: FINALIZE_REQ_LEN,
                actual_len: out.len(),
            });
        }
        let (acc_bytes, rest) = out.split_at_mut(8);
        acc_bytes.copy_from_slice(&self.account_id.to_be_bytes());

        let (cookie_bytes, proof_bytes) = rest.split_at_mut(32);
        cookie_bytes.copy_from_slice(&self.auth_cookie);
        if let Some(dst) = proof_bytes.get_mut(..32) {
            dst.copy_from_slice(&self.client_proof);
        }
        Ok(FINALIZE_REQ_LEN)
    }

    /// Parses request from raw byte slice with strict bounds checking.
    pub fn read_from(src: &[u8]) -> Result<Self, NetError> {
        if src.len() < FINALIZE_REQ_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: FINALIZE_REQ_LEN,
                actual_len: src.len(),
            });
        }
        let mut acc_buf = [0u8; 8];
        if let Some(s) = src.get(..8) {
            acc_buf.copy_from_slice(s);
        }
        let account_id = u64::from_be_bytes(acc_buf);

        let mut auth_cookie = [0u8; 32];
        if let Some(s) = src.get(8..40) {
            auth_cookie.copy_from_slice(s);
        }

        let mut client_proof = [0u8; 32];
        if let Some(s) = src.get(40..72) {
            client_proof.copy_from_slice(s);
        }

        Ok(Self {
            account_id,
            auth_cookie,
            client_proof,
        })
    }
}

/// Server finalization response confirming session activation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConnectFinalizeResponse {
    /// Assigned ephemeral session identifier.
    pub session_id: u64,
    /// Initial authority epoch granted for the session.
    pub authority_epoch: u32,
    /// Server proof confirming authentication legitimacy to client.
    pub server_proof: [u8; 32],
}

impl ConnectFinalizeResponse {
    /// Encodes response into destination byte slice.
    pub fn write_to(&self, out: &mut [u8]) -> Result<usize, NetError> {
        if out.len() < FINALIZE_RESP_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: FINALIZE_RESP_LEN,
                actual_len: out.len(),
            });
        }
        let (sess_bytes, rest) = out.split_at_mut(8);
        sess_bytes.copy_from_slice(&self.session_id.to_be_bytes());

        let (epoch_bytes, proof_bytes) = rest.split_at_mut(4);
        epoch_bytes.copy_from_slice(&self.authority_epoch.to_be_bytes());
        if let Some(dst) = proof_bytes.get_mut(..32) {
            dst.copy_from_slice(&self.server_proof);
        }
        Ok(FINALIZE_RESP_LEN)
    }

    /// Parses response from raw byte slice with strict bounds checking.
    pub fn read_from(src: &[u8]) -> Result<Self, NetError> {
        if src.len() < FINALIZE_RESP_LEN {
            return Err(NetError::TruncatedPacket {
                expected_len: FINALIZE_RESP_LEN,
                actual_len: src.len(),
            });
        }
        let mut sess_buf = [0u8; 8];
        if let Some(s) = src.get(..8) {
            sess_buf.copy_from_slice(s);
        }
        let session_id = u64::from_be_bytes(sess_buf);

        let mut epoch_buf = [0u8; 4];
        if let Some(s) = src.get(8..12) {
            epoch_buf.copy_from_slice(s);
        }
        let authority_epoch = u32::from_be_bytes(epoch_buf);

        let mut server_proof = [0u8; 32];
        if let Some(s) = src.get(12..44) {
            server_proof.copy_from_slice(s);
        }

        Ok(Self {
            session_id,
            authority_epoch,
            server_proof,
        })
    }
}

/// Circular 64-bit sliding replay window preventing duplicate and replayed datagrams.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReplayWindow {
    /// Highest packet sequence number accepted so far.
    highest_sequence: u64,
    /// Bitmask of 64 sequences preceding `highest_sequence`.
    /// Bit 0 corresponds to `highest_sequence`. Bit k corresponds to `highest_sequence - k`.
    window: u64,
}

impl Default for ReplayWindow {
    fn default() -> Self {
        Self::new()
    }
}

impl ReplayWindow {
    /// Creates a new empty replay window.
    pub fn new() -> Self {
        Self {
            highest_sequence: 0,
            window: 0,
        }
    }

    /// Checks if a sequence number is acceptable, and updates the window if valid.
    ///
    /// Returns `Ok(())` if packet is in-window and not a duplicate.
    /// Returns `Err(NetError::ReplayDetected)` if packet was already received or is too old.
    pub fn check_and_update(&mut self, sequence: u64) -> Result<(), NetError> {
        if self.window == 0 && self.highest_sequence == 0 {
            // First packet received
            self.highest_sequence = sequence;
            self.window = 1;
            return Ok(());
        }

        if sequence > self.highest_sequence {
            let diff = sequence - self.highest_sequence;
            if diff < 64 {
                self.window <<= diff;
                self.window |= 1;
            } else {
                self.window = 1;
            }
            self.highest_sequence = sequence;
            Ok(())
        } else {
            let diff = self.highest_sequence - sequence;
            if diff >= 64 {
                return Err(NetError::ReplayDetected {
                    sequence,
                    window_bottom: self.highest_sequence.saturating_sub(63),
                });
            }
            let mask = 1u64 << diff;
            if (self.window & mask) != 0 {
                return Err(NetError::ReplayDetected {
                    sequence,
                    window_bottom: self.highest_sequence.saturating_sub(63),
                });
            }
            self.window |= mask;
            Ok(())
        }
    }

    /// Returns the current highest sequence observed.
    #[inline]
    pub fn highest_sequence(&self) -> u64 {
        self.highest_sequence
    }
}

/// Security and cryptographic context for an active authenticated client session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionSecurityContext {
    /// Ephemeral session identifier.
    pub session_id: u64,
    /// Authenticated account identifier.
    pub account_id: u64,
    /// Active authority epoch for this session.
    pub authority_epoch: u32,
    /// Symmetric session key derived from handshake.
    pub session_key: [u8; 32],
    /// Monotonic sequence replay window.
    pub replay_window: ReplayWindow,
    /// Tick when session was established.
    pub created_at_tick: u64,
    /// Tick when last valid packet was received.
    pub last_seen_tick: u64,
    /// Maximum ticks of inactivity before session expiry.
    pub ttl_ticks: u64,
}

impl SessionSecurityContext {
    /// Creates a new authenticated session context.
    pub fn new(
        session_id: u64,
        account_id: u64,
        authority_epoch: u32,
        session_key: [u8; 32],
        current_tick: u64,
        ttl_ticks: u64,
    ) -> Self {
        Self {
            session_id,
            account_id,
            authority_epoch,
            session_key,
            replay_window: ReplayWindow::new(),
            created_at_tick: current_tick,
            last_seen_tick: current_tick,
            ttl_ticks,
        }
    }

    /// Checks whether the session has expired due to inactivity.
    #[inline]
    pub fn is_expired(&self, current_tick: u64) -> bool {
        current_tick.saturating_sub(self.last_seen_tick) > self.ttl_ticks
    }

    /// Updates the last active tick timestamp.
    #[inline]
    pub fn touch(&mut self, current_tick: u64) {
        if current_tick > self.last_seen_tick {
            self.last_seen_tick = current_tick;
        }
    }

    /// Validates an incoming packet sequence number against the session replay window.
    #[inline]
    pub fn validate_sequence(&mut self, sequence: u64) -> Result<(), NetError> {
        self.replay_window.check_and_update(sequence)
    }
}

/// Computes an authentication cookie for the challenge response using server secret key.
pub fn compute_auth_cookie(
    server_secret: &[u8],
    account_id: u64,
    client_nonce: &[u8; NONCE_LEN],
    server_nonce: &[u8; NONCE_LEN],
) -> [u8; 32] {
    let mut payload = [0u8; 8 + NONCE_LEN + NONCE_LEN];
    let (acc_dst, rest) = payload.split_at_mut(8);
    acc_dst.copy_from_slice(&account_id.to_be_bytes());

    let (cn_dst, sn_dst) = rest.split_at_mut(NONCE_LEN);
    cn_dst.copy_from_slice(client_nonce);
    sn_dst.copy_from_slice(server_nonce);

    hmac_sha256(server_secret, &payload)
}

/// Computes client proof of authentication token over cookie and nonces.
pub fn compute_client_proof(
    account_token: &[u8],
    auth_cookie: &[u8; 32],
    client_nonce: &[u8; NONCE_LEN],
    server_nonce: &[u8; NONCE_LEN],
) -> [u8; 32] {
    let mut payload = [0u8; 32 + NONCE_LEN + NONCE_LEN];
    let (c_dst, rest) = payload.split_at_mut(32);
    c_dst.copy_from_slice(auth_cookie);

    let (cn_dst, sn_dst) = rest.split_at_mut(NONCE_LEN);
    cn_dst.copy_from_slice(client_nonce);
    sn_dst.copy_from_slice(server_nonce);

    hmac_sha256(account_token, &payload)
}

/// Verifies client proof against expected proof using constant-time comparison.
pub fn verify_client_proof(
    account_token: &[u8],
    auth_cookie: &[u8; 32],
    client_nonce: &[u8; NONCE_LEN],
    server_nonce: &[u8; NONCE_LEN],
    provided_proof: &[u8; 32],
) -> bool {
    let expected = compute_client_proof(account_token, auth_cookie, client_nonce, server_nonce);
    constant_time_eq(&expected, provided_proof)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_challenge_request_roundtrip() {
        let req = ConnectChallengeRequest {
            account_id: 100459,
            client_nonce: [7u8; NONCE_LEN],
            protocol_version: 1,
        };
        let mut buf = [0u8; CHALLENGE_REQ_LEN];
        assert_eq!(req.write_to(&mut buf).unwrap(), CHALLENGE_REQ_LEN);
        let parsed = ConnectChallengeRequest::read_from(&buf).unwrap();
        assert_eq!(req, parsed);
    }

    #[test]
    fn test_challenge_response_roundtrip() {
        let resp = ConnectChallengeResponse {
            server_nonce: [9u8; NONCE_LEN],
            auth_cookie: [0xABu8; 32],
        };
        let mut buf = [0u8; CHALLENGE_RESP_LEN];
        assert_eq!(resp.write_to(&mut buf).unwrap(), CHALLENGE_RESP_LEN);
        let parsed = ConnectChallengeResponse::read_from(&buf).unwrap();
        assert_eq!(resp, parsed);
    }

    #[test]
    fn test_finalize_request_roundtrip() {
        let req = ConnectFinalizeRequest {
            account_id: 88831,
            auth_cookie: [0x55u8; 32],
            client_proof: [0x77u8; 32],
        };
        let mut buf = [0u8; FINALIZE_REQ_LEN];
        assert_eq!(req.write_to(&mut buf).unwrap(), FINALIZE_REQ_LEN);
        let parsed = ConnectFinalizeRequest::read_from(&buf).unwrap();
        assert_eq!(req, parsed);
    }

    #[test]
    fn test_finalize_response_roundtrip() {
        let resp = ConnectFinalizeResponse {
            session_id: 9991234,
            authority_epoch: 1,
            server_proof: [0x11u8; 32],
        };
        let mut buf = [0u8; FINALIZE_RESP_LEN];
        assert_eq!(resp.write_to(&mut buf).unwrap(), FINALIZE_RESP_LEN);
        let parsed = ConnectFinalizeResponse::read_from(&buf).unwrap();
        assert_eq!(resp, parsed);
    }

    #[test]
    fn test_replay_window_in_order() {
        let mut window = ReplayWindow::new();
        for seq in 1..=100 {
            assert!(window.check_and_update(seq).is_ok());
        }
    }

    #[test]
    fn test_replay_window_duplicate_detection() {
        let mut window = ReplayWindow::new();
        assert!(window.check_and_update(10).is_ok());
        assert!(window.check_and_update(11).is_ok());
        assert!(window.check_and_update(10).is_err());
    }

    #[test]
    fn test_replay_window_out_of_order_within_64() {
        let mut window = ReplayWindow::new();
        assert!(window.check_and_update(50).is_ok());
        assert!(window.check_and_update(40).is_ok());
        assert!(window.check_and_update(45).is_ok());
        assert!(window.check_and_update(40).is_err());
    }

    #[test]
    fn test_replay_window_outside_64_dropped() {
        let mut window = ReplayWindow::new();
        assert!(window.check_and_update(100).is_ok());
        assert!(window.check_and_update(35).is_err()); // 100 - 35 = 65 >= 64
        assert!(window.check_and_update(36).is_err()); // 100 - 36 = 64 >= 64
        assert!(window.check_and_update(37).is_ok()); // 100 - 37 = 63 < 64 (valid)
    }

    #[test]
    fn test_client_proof_verification() {
        let server_secret = b"server_top_secret_key_123456789";
        let account_token = b"client_auth_token_secret_987654";
        let account_id = 42u64;
        let client_nonce = [1u8; NONCE_LEN];
        let server_nonce = [2u8; NONCE_LEN];

        let auth_cookie =
            compute_auth_cookie(server_secret, account_id, &client_nonce, &server_nonce);
        let valid_proof =
            compute_client_proof(account_token, &auth_cookie, &client_nonce, &server_nonce);

        assert!(verify_client_proof(
            account_token,
            &auth_cookie,
            &client_nonce,
            &server_nonce,
            &valid_proof
        ));

        let mut corrupted_proof = valid_proof;
        corrupted_proof[0] ^= 0xFF;
        assert!(!verify_client_proof(
            account_token,
            &auth_cookie,
            &client_nonce,
            &server_nonce,
            &corrupted_proof
        ));
    }
}
