[package]
name = "eidolon-world"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Seamless open-world zone management, ephemeral dungeon instancing, and gacha account hibernation."

[lints]
workspace = true

[dependencies]
eidolon-core = { workspace = true }
eidolon-spatial = { workspace = true }
eidolon-net = { workspace = true }
